name: coverage_report
description: A simple command-line application.
version: 1.0.0
environment:
  sdk: ">=2.11.0"
executables:
  coverage-report:
dev_dependencies:
  lints: ^1.0.0
dependencies:
  args: ^2.3.0
  meta: ^1.7.0
